name: Symfony
on:
  push:
    branches: [ main ]
jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use PHPunit
        run: vendor/bin/phpunit